name: commonplace
dependencies:
- dateutil=2.4.1=py34_0
- flake8=2.3.0=py34_0
- flask=0.10.1=py34_1
- itsdangerous=0.24=py34_0
- jinja2=2.8=py34_0
- markupsafe=0.23=py34_0
- mccabe=0.3=py34_1
- openssl=1.0.1k=1
- pep8=1.6.2=py34_0
- pip=7.1.0=py34_1
- pyflakes=0.9.2=py34_0
- python=3.4.3=1
- readline=6.2=2
- setuptools=18.1=py34_0
- six=1.9.0=py34_0
- sqlalchemy=1.0.8=py34_0
- sqlite=3.8.4.1=1
- system=5.8=2
- tk=8.5.18=0
- werkzeug=0.10.4=py34_0
- wheel=0.24.0=py34_0
- xz=5.0.5=0
- zlib=1.2.8=0
- pip:
  - flask-sqlalchemy==2.0
  - python-dateutil==2.4.1

